/** Lucide-иконки для пунктов быта / ухода / работы — у каждого свой контур */
export const LIFE_PULSE_ICON: Record<string, string> = {
  // работа
  focus: "Target",
  tasks: "ListChecks",
  meeting: "Users",
  plan: "CalendarDays",
  learn_job: "GraduationCap",
  boundary: "Ban",
  remote: "Laptop",
  calls: "Phone",
  admin: "FileText",
  creative_work: "Lightbulb",
  overtime: "Clock",
  side_project: "Rocket",
  lunch_break: "Coffee",
  presentation: "Presentation",
  email_batch: "Mail",
  deep_work: "Brain",
  cowork: "Building2",
  // уход
  skincare: "Sparkles",
  face_mask: "Smile",
  bath_ritual: "Bath",
  massage: "Hand",
  hair: "Scissors",
  rest_eyes: "Eye",
  walk_solo: "Footprints",
  meditation: "Flower2",
  journal: "BookOpen",
  tea_ritual: "Coffee",
  nap: "Moon",
  nails: "Paintbrush",
  stretch_care: "StretchHorizontal",
  spa: "Thermometer",
  makeup: "Palette",
  sauna_home: "Flame",
  manicure: "Sparkles",
  facial: "Droplets",
  // быт
  clean_15: "Sparkles",
  dishes: "UtensilsCrossed",
  laundry: "Shirt",
  meal_prep: "ChefHat",
  groceries: "ShoppingCart",
  organize: "LayoutGrid",
  bed_make: "BedDouble",
  trash: "Trash2",
  plants: "Flower2",
  paperwork: "FileText",
  deep_clean: "SprayCan",
  fridge: "Refrigerator",
  pet_home: "Cat",
  repair: "Wrench",
  shop: "Store",
  cook_prep: "CookingPot",
  ironing: "Shirt",
};

export function lifePulseIconName(itemId: string): string {
  return LIFE_PULSE_ICON[itemId] ?? "Circle";
}
